# **NUMPY**

In [1]:
# import numpy Library
import numpy as np

In [2]:
# first numpy array
firstDArray = np.array([1, 2, 3, 4, 5, 6])

In [3]:
# print first array
firstDArray

array([1, 2, 3, 4, 5, 6])

In [4]:
# array with zeros
np.zeros((2, 3), dtype = "int64")

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
# array with ones
np.ones((3, 4), dtype = "float32")

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [6]:
# array with empty
np.empty((2, 4))

array([[2.30804071e-316, 3.60739284e-313, 7.90505033e-323,
        2.30803992e-316],
       [0.00000000e+000, 0.00000000e+000, 9.88131292e-324,
        0.00000000e+000]])

In [7]:
# array with arange method
npArange = np.arange(10, 110, 10)
npArange

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
# reshape method to change/create array
np.reshape(npArange, (2, 5))

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [9]:
# linspace for linearly (equal) spaced data elements
linspaceArray = np.linspace(1, 50, num = 100, dtype="float32")

In [10]:
# print linspace array
linspaceArray

array([ 1.       ,  1.4949495,  1.989899 ,  2.4848485,  2.979798 ,
        3.4747474,  3.969697 ,  4.4646463,  4.959596 ,  5.4545455,
        5.949495 ,  6.4444447,  6.939394 ,  7.4343433,  7.929293 ,
        8.424242 ,  8.919192 ,  9.414142 ,  9.909091 , 10.40404  ,
       10.89899  , 11.393939 , 11.888889 , 12.383839 , 12.878788 ,
       13.373737 , 13.868687 , 14.363636 , 14.858586 , 15.353536 ,
       15.848485 , 16.343435 , 16.838385 , 17.333334 , 17.828283 ,
       18.323233 , 18.818182 , 19.313131 , 19.80808  , 20.30303  ,
       20.79798  , 21.292929 , 21.787878 , 22.282827 , 22.777779 ,
       23.272728 , 23.767677 , 24.262627 , 24.757576 , 25.252525 ,
       25.747475 , 26.242424 , 26.737373 , 27.232323 , 27.727272 ,
       28.222221 , 28.717173 , 29.212122 , 29.707071 , 30.20202  ,
       30.69697  , 31.19192  , 31.686869 , 32.18182  , 32.67677  ,
       33.17172  , 33.666668 , 34.161617 , 34.656567 , 35.151516 ,
       35.646465 , 36.141415 , 36.636364 , 37.131313 , 37.6262

In [11]:
# one dimentional array
oneDArray = np.array([3, 4, 5, 6, 7])
print(oneDArray)

# no of dimentions
oneDArray.ndim

[3 4 5 6 7]


1

In [12]:
# two dimentional array
twoDArray = np.array([[3, 4, 5, 6], [6, 7, 8, 7], [6, 3, 2, 5]])
print(twoDArray)

# no of dimentions
twoDArray.ndim

[[3 4 5 6]
 [6 7 8 7]
 [6 3 2 5]]


2

In [13]:
# three dimentional array
threeDArray = np.array([[[3, 4, 5], [5, 6, 4]],
                        [[3, 4, 5], [5, 6, 4]], 
                        [[3, 4, 5], [5, 6, 4]],
                        [[3, 4, 5], [5, 6, 4]]])
print(threeDArray)


# no of dimentions
threeDArray.ndim

[[[3 4 5]
  [5 6 4]]

 [[3 4 5]
  [5 6 4]]

 [[3 4 5]
  [5 6 4]]

 [[3 4 5]
  [5 6 4]]]


3

In [14]:
# four dimentional array
fourDarray = np.array([[[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]],
                        
                       [[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]],
                        
                       [[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]],
                        
                       [[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]]])
print(fourDarray)

# no of dimentions
fourDarray.ndim

[[[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]]


4

In [15]:
# shape of fourDarray
fourDarray.shape

(4, 3, 2, 3)