<a href="https://colab.research.google.com/github/kamipakistan/Data-Science-with-Python/blob/main/01_Numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [1]:
# import numpy Library
import numpy as np

In [2]:
# first numpy array
firstDArray = np.array([1, 2, 3, 4, 5, 6])

In [3]:
# print first array
firstDArray

array([1, 2, 3, 4, 5, 6])

In [4]:
# array with zeros
np.zeros((2, 3), dtype = "int64")

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
# array with ones
np.ones((3, 4), dtype = "float32")

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [6]:
# array with empty
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# array with arange method
npArange = np.arange(10, 110, 10)
npArange

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
# reshape method to change/create array
np.reshape(npArange, (2, 5))

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [9]:
# linspace for linearly (equal) spaced data elements
linspaceArray = np.linspace(1, 50, num = 100, dtype="float32")

In [10]:
# print linspace array
linspaceArray

array([ 1.       ,  1.4949495,  1.989899 ,  2.4848485,  2.979798 ,
        3.4747474,  3.969697 ,  4.4646463,  4.959596 ,  5.4545455,
        5.949495 ,  6.4444447,  6.939394 ,  7.4343433,  7.929293 ,
        8.424242 ,  8.919192 ,  9.414142 ,  9.909091 , 10.40404  ,
       10.89899  , 11.393939 , 11.888889 , 12.383839 , 12.878788 ,
       13.373737 , 13.868687 , 14.363636 , 14.858586 , 15.353536 ,
       15.848485 , 16.343435 , 16.838385 , 17.333334 , 17.828283 ,
       18.323233 , 18.818182 , 19.313131 , 19.80808  , 20.30303  ,
       20.79798  , 21.292929 , 21.787878 , 22.282827 , 22.777779 ,
       23.272728 , 23.767677 , 24.262627 , 24.757576 , 25.252525 ,
       25.747475 , 26.242424 , 26.737373 , 27.232323 , 27.727272 ,
       28.222221 , 28.717173 , 29.212122 , 29.707071 , 30.20202  ,
       30.69697  , 31.19192  , 31.686869 , 32.18182  , 32.67677  ,
       33.17172  , 33.666668 , 34.161617 , 34.656567 , 35.151516 ,
       35.646465 , 36.141415 , 36.636364 , 37.131313 , 37.6262

In [11]:
# one dimentional array
oneDArray = np.array([3, 4, 5, 6, 7])
print(oneDArray)

# no of dimentions
oneDArray.ndim

[3 4 5 6 7]


1

In [12]:
# two dimentional array
twoDArray = np.array([[3, 4, 5, 6], [6, 7, 8, 7], [6, 3, 2, 5]])
print(twoDArray)

# no of dimentions
twoDArray.ndim

[[3 4 5 6]
 [6 7 8 7]
 [6 3 2 5]]


2

In [13]:
# three dimentional array
threeDArray = np.array([[[3, 4, 5], [5, 6, 4]],
                        [[3, 4, 5], [5, 6, 4]], 
                        [[3, 4, 5], [5, 6, 4]],
                        [[3, 4, 5], [5, 6, 4]]])
print(threeDArray)


# no of dimentions
threeDArray.ndim

[[[3 4 5]
  [5 6 4]]

 [[3 4 5]
  [5 6 4]]

 [[3 4 5]
  [5 6 4]]

 [[3 4 5]
  [5 6 4]]]


3

In [14]:
# four dimentional array
fourDarray = np.array([[[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]],
                        
                       [[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]],
                        
                       [[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]],
                        
                       [[[1, 1, 1],
                         [1, 1, 1]], 
                        [[2, 2, 2],
                         [2, 2, 2]], 
                        [[2, 2, 2],
                         [2, 2, 2]]]])
print(fourDarray)

# no of dimentions
fourDarray.ndim

[[[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]]]]


4

In [15]:
# shape of fourDarray
fourDarray.shape

(4, 3, 2, 3)

# **Universal Functions in Numpy**

In [16]:
twoDArray

array([[3, 4, 5, 6],
       [6, 7, 8, 7],
       [6, 3, 2, 5]])

In [18]:
# privide the sqrt of each element in the provided array
np.sqrt(twoDArray)

array([[1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.44948974, 2.64575131, 2.82842712, 2.64575131],
       [2.44948974, 1.73205081, 1.41421356, 2.23606798]])

In [20]:
# gives cosine values of all the element in the array
np.cos(twoDArray)

array([[-0.9899925 , -0.65364362,  0.28366219,  0.96017029],
       [ 0.96017029,  0.75390225, -0.14550003,  0.75390225],
       [ 0.96017029, -0.9899925 , -0.41614684,  0.28366219]])

In [21]:
# perform exponential on each element
np.exp(twoDArray)

array([[  20.08553692,   54.59815003,  148.4131591 ,  403.42879349],
       [ 403.42879349, 1096.63315843, 2980.95798704, 1096.63315843],
       [ 403.42879349,   20.08553692,    7.3890561 ,  148.4131591 ]])

In [24]:
# Return the largest integer value of each element
np.floor(np.cos(twoDArray))

array([[-1., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0., -1., -1.,  0.]])

## **Shape Manipulation**

In [28]:
# creating array for manipulation
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
# Reshaping the elememet
arrReshaped = arr.reshape(4, 25)
arrReshaped

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
# Flattens the dataset
arrayFlattened = arrReshaped.flatten()
arrayFlattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
# Flattens the dataset
arrayFlattened = arrReshaped.ravel()
arrayFlattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
# Stacking two array
# note that all input arrays must have the same shape
np.stack((arrayFlattened, arrayFlattened))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [56]:
# resizing 
arrReshaped.resize(5, 20)
arrReshaped

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [58]:
# Split an array into multiple sub-arrays horizontally (column-wise).
np.hsplit(arrReshaped, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]